name: CLL Auto Post
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install FFmpeg and Deps
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
          pip install telethon requests

      - name: Run script
        env:
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
          TG_SESSION: ${{ secrets.TG_SESSION }}
          IG_BUSINESS_ID: ${{ secrets.IG_BUSINESS_ID }}
          IG_PAGE_TOKEN: ${{ secrets.IG_PAGE_TOKEN }}
        run: python main.py

      - name: Save and Push
        run: |
          git config --global user.name 'CLL-Bot'
          git config --global user.email 'bot@catanialatinlovers.it'
          git add pubblicati.txt ready.mp4 || true
          git stash # Mette al sicuro i cambiamenti locali
          git pull --rebase origin main # Scarica gli aggiornamenti remoti
          git stash pop || true # Riaplica i cambiamenti sopra i nuovi dati
          git add pubblicati.txt ready.mp4 || true
          git commit -m "Update HQ video and database" || true
          git push origin main
