name: CLL Auto Post

on:
  schedule:
    - cron: '0 * * * *' # Gira ogni ora spaccata
  workflow_dispatch: # Permette l'avvio manuale dal tasto "Run workflow"

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Obbligatorio per pushare pubblicati.txt e i video nel repo privato
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install FFmpeg and Deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install telethon requests

      - name: Run script
        env:
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
          TG_SESSION: ${{ secrets.TG_SESSION }}
          IG_BUSINESS_ID: ${{ secrets.IG_BUSINESS_ID }}
          IG_PAGE_TOKEN: ${{ secrets.IG_PAGE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Passa il token automatico allo script Python
        run: python main.py

      - name: Save progress
        run: |
          git config --global user.name 'CLL-Bot'
          git config --global user.email 'bot@catanialatinlovers.it'
          git add pubblicati.txt || true
          git add *.mp4 || true
          git commit -m "Aggiornamento database post e video" || true
          git push || true
